config/routes.rb
Rails.application.routes.draw do
  resources :documents, only: [:show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  constraints format: :json do
    resources :webhooks, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  has_many :matched_keywords
  has_many :key_phrases
  has_one :source
end

app/models/key_phrase.rb
class KeyPhrase < ApplicationRecord
  belongs_to :document
end

app/models/matched_keyword.rb
class MatchedKeyword < ApplicationRecord
  belongs_to :document
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.order(publish_date: :desc).limit(20)
  end

  def show
    @document = Document.find(params[:id])
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    documents = DocumentParser.new(request.raw_post).parse_documents
    Rails.logger.debug(documents.inspect)

    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>
<h3>(Latest 20 results)</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Sentiment</th>
      <th>Published</th>
      <th>Image</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= document.sentiment %></td>
        <td><%= time_ago_in_words(document.publish_date) %></td>
        <td><%= image_tag(document.image_link, height: '32', width: '32') if document.image_link.present? %></td>
        <td><%= link_to 'Show', document %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Document ID:</b>
  <%= @document.meltwater_uuid %>
</p>

<p>
  <b>Title:</b>
  <%= @document.title %>
</p>

<p>
  <b>Author:</b>
  <%= @document.author %>
</p>

<p>
  <b>Hit Sentence:</b>
  <%= @document.hit_sentence %>
</p>

<p>
  <b>Sentiment:</b>
  <%= @document.sentiment %>
</p>

<p>
  <b>City:</b>
  <%= @document.city %>
</p>

<p>
  <b>Region:</b>
  <%= @document.region %>
</p>

<p>
  <b>Meta - Search Name:</b>
  <%= @document.search_name %>
</p>

<p>
  <b>Meta - Search ID:</b>
  <%= @document.search_id %>
</p>

<p>
  <b>Meta - Hook ID:</b>
  <%= @document.hook_id %>
</p>

<p>
  <b>Key Phrases:</b><br/>
  <% @document.key_phrases.each do |key_phrase| %>
    Phrase: <%= key_phrase.phrase %><br/>
    Relevance: <%= key_phrase.relevance %><br/>
  <% end %>
</p>

<p>
  <b>Matched Keywords:</b><br/>
  <% @document.matched_keywords.each do |matched_keyword| %>
    <%= matched_keyword.value %><br/>
  <% end %>
</p>

<p>
  <b>Image:</b><br/>
  <% if @document.image_link.present? %>
    <%= image_tag(@document.image_link) %></td>
<% end %>
</p>

<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StreamingRelationalDatabase</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>